# Homebrew Bundle
# https://github.com/Homebrew/homebrew-bundle

# ------------------------------------------------------------------------------
# CLI Tools
# ------------------------------------------------------------------------------
brew "git"
brew "zsh"
brew "zsh-completions"
brew "node"
brew "sheldon"
brew "coreutils"
brew "tree"
brew "lsd"
brew "wget"
brew "yarn"
brew "pnpm"
brew "tldr"
brew "mas"
brew "gh"
brew "terminal-notifier"
brew "wifi-password"
brew "speedtest"
brew "bat"
brew "trash-it"
brew "youtube-dl"
brew "starship"
brew "watchman" # Watching files for Jest

# ------------------------------------------------------------------------------
# Taps
# ------------------------------------------------------------------------------
tap "homebrew/cask-fonts"

# ------------------------------------------------------------------------------
# Cask
# ------------------------------------------------------------------------------

# Fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hasklug-nerd-font"

# Utils
cask "gpg-suite"
cask "openvpn-connect"

# Media
cask "handbrake"

# Development
cask "fig"
cask "iterm2"
cask "visual-studio-code"
cask "github"

# Development php
brew "composer"
brew "mariadb"
brew "mailhog"
brew "wp-cli"

# Desktop applications
cask "telegram"
cask "google-chrome"
cask "firefox"
cask "brave-browser"
cask "slack"
cask "spotify"
cask "notion"
cask "discord"
cask "postman"

# Quick Look plugins
cask "qlcolorcode" # https://github.com/anthonygelibert/QLColorCode
cask "qlstephen" # https://github.com/whomwah/qlstephen
cask "quicklook-json" # https://github.com/sindresorhus/quick-look-plugins
cask "qlimagesize" # https://github.com/Nyx0uf/qlImageSize
cask "webpquicklook" # https://github.com/dchest/webp-quicklook
